# Generated by Django 4.2.4 on 2023-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.TextField(verbose_name='Themes')),
                ('number_solutions', models.IntegerField(blank=True, null=True, verbose_name='Number solutions')),
                ('problem_name', models.CharField(max_length=300, verbose_name='Problem name')),
                ('number', models.CharField(max_length=200, verbose_name='Number')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is_used')),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problems',
            },
        ),
    ]
